#!/bin/bash
pacman -S --needed --noconfirm a52dec
pacman -S --needed --noconfirm aalib
pacman -S --needed --noconfirm accountsservice
pacman -S --needed --noconfirm acl
pacman -S --needed --noconfirm acpi
pacman -S --needed --noconfirm acpid
pacman -S --needed --noconfirm adwaita-icon-theme
pacman -S --needed --noconfirm alsa-firmware
pacman -S --needed --noconfirm alsa-lib
pacman -S --needed --noconfirm alsa-plugins
pacman -S --needed --noconfirm alsa-utils
pacman -S --needed --noconfirm android-tools
pacman -S --needed --noconfirm android-udev
pacman -S --needed --noconfirm appstream-glib
pacman -S --needed --noconfirm apr
pacman -S --needed --noconfirm apr-util
pacman -S --needed --noconfirm archlinux-appstream-data
pacman -S --needed --noconfirm archlinux-keyring
pacman -S --needed --noconfirm aria2
pacman -S --needed --noconfirm aspell
pacman -S --needed --noconfirm at-spi2-atk
pacman -S --needed --noconfirm at-spi2-core
pacman -S --needed --noconfirm atk
pacman -S --needed --noconfirm atkmm
pacman -S --needed --noconfirm attr
pacman -S --needed --noconfirm audacious
pacman -S --needed --noconfirm audacious-plugins
pacman -S --needed --noconfirm autoconf
pacman -S --needed --noconfirm automake
pacman -S --needed --noconfirm avahi
pacman -S --needed --noconfirm b43-fwcutter
pacman -S --needed --noconfirm babl
pacman -S --needed --noconfirm bash
pacman -S --needed --noconfirm bc
pacman -S --needed --noconfirm binutils
pacman -S --needed --noconfirm bison
pacman -S --needed --noconfirm blas
pacman -S --needed --noconfirm blueman
pacman -S --needed --noconfirm bluez
pacman -S --needed --noconfirm bluez-libs
pacman -S --needed --noconfirm boost
pacman -S --needed --noconfirm boost-libs
pacman -S --needed --noconfirm breath-wallpaper
pacman -S --needed --noconfirm btrfs-progs
pacman -S --needed --noconfirm bzip2
pacman -S --needed --noconfirm c-ares
pacman -S --needed --noconfirm ca-certificates
pacman -S --needed --noconfirm ca-certificates-cacert
pacman -S --needed --noconfirm ca-certificates-mozilla
pacman -S --needed --noconfirm ca-certificates-utils
pacman -S --needed --noconfirm cairo
pacman -S --needed --noconfirm cairomm
pacman -S --needed --noconfirm cantarell-fonts
pacman -S --needed --noconfirm catfish
pacman -S --needed --noconfirm cblas
pacman -S --needed --noconfirm cdparanoia
pacman -S --needed --noconfirm celt
pacman -S --needed --noconfirm cfitsio
pacman -S --needed --noconfirm chromaprint
pacman -S --needed --noconfirm cifs-utils
pacman -S --needed --noconfirm ckbcomp
pacman -S --needed --noconfirm clang
pacman -S --needed --noconfirm clucene
pacman -S --needed --noconfirm cmake
pacman -S --needed --noconfirm colord
pacman -S --needed --noconfirm compositeproto
pacman -S --needed --noconfirm coreutils
pacman -S --needed --noconfirm cpupower
pacman -S --needed --noconfirm cracklib
pacman -S --needed --noconfirm crda
pacman -S --needed --noconfirm cronie
pacman -S --needed --noconfirm cryptsetup
pacman -S --needed --noconfirm cups
pacman -S --needed --noconfirm cups-filters
pacman -S --needed --noconfirm cups-pdf
pacman -S --needed --noconfirm cups-pk-helper
pacman -S --needed --noconfirm curl
pacman -S --needed --noconfirm daala
pacman -S --needed --noconfirm damageproto
pacman -S --needed --noconfirm db
pacman -S --needed --noconfirm dbus
pacman -S --needed --noconfirm dbus-glib
pacman -S --needed --noconfirm dconf
pacman -S --needed --noconfirm desktop-file-utils
pacman -S --needed --noconfirm device-mapper
pacman -S --needed --noconfirm dhclient
pacman -S --needed --noconfirm dhcpcd
pacman -S --needed --noconfirm diffutils
pacman -S --needed --noconfirm ding-libs
pacman -S --needed --noconfirm djvulibre
pacman -S --needed --noconfirm dmidecode
pacman -S --needed --noconfirm dmraid
pacman -S --needed --noconfirm dnsmasq
pacman -S --needed --noconfirm dnssec-anchors
pacman -S --needed --noconfirm dosfstools
pacman -S --needed --noconfirm dotnet-host
pacman -S --needed --noconfirm double-conversion
pacman -S --needed --noconfirm e2fsprogs
pacman -S --needed --noconfirm ecryptfs-utils
pacman -S --needed --noconfirm enchant
pacman -S --needed --noconfirm engrampa
pacman -S --needed --noconfirm engrampa-thunar-plugin
pacman -S --needed --noconfirm exfat-utils
pacman -S --needed --noconfirm exiv2
pacman -S --needed --noconfirm exo
pacman -S --needed --noconfirm expat
pacman -S --needed --noconfirm f2fs-tools
pacman -S --needed --noconfirm faac
pacman -S --needed --noconfirm faad2
pacman -S --needed --noconfirm fakeroot
pacman -S --needed --noconfirm farstream
pacman -S --needed --noconfirm ffmpeg
pacman -S --needed --noconfirm ffmpegthumbnailer
pacman -S --needed --noconfirm ffms2
pacman -S --needed --noconfirm fftw
pacman -S --needed --noconfirm file
pacman -S --needed --noconfirm filesystem
pacman -S --needed --noconfirm findutils
pacman -S --needed --noconfirm firefox
pacman -S --needed --noconfirm fixesproto
pacman -S --needed --noconfirm flac
pacman -S --needed --noconfirm flex
pacman -S --needed --noconfirm fontconfig
pacman -S --needed --noconfirm fontsproto
pacman -S --needed --noconfirm foomatic-db-engine
pacman -S --needed --noconfirm freeglut
pacman -S --needed --noconfirm freetype2
pacman -S --needed --noconfirm fribidi
pacman -S --needed --noconfirm ftgl
pacman -S --needed --noconfirm fuse-common
pacman -S --needed --noconfirm fuse2
pacman -S --needed --noconfirm galculator-gtk2
pacman -S --needed --noconfirm gamin
pacman -S --needed --noconfirm garcon
pacman -S --needed --noconfirm gawk
pacman -S --needed --noconfirm gc
pacman -S --needed --noconfirm gcab
pacman -S --needed --noconfirm gcc
pacman -S --needed --noconfirm gcc-libs
pacman -S --needed --noconfirm gconf
pacman -S --needed --noconfirm gcr
pacman -S --needed --noconfirm gd
pacman -S --needed --noconfirm gdbm
pacman -S --needed --noconfirm gdk-pixbuf2
pacman -S --needed --noconfirm geoclue2
pacman -S --needed --noconfirm gettext
pacman -S --needed --noconfirm ghostscript
pacman -S --needed --noconfirm giflib
pacman -S --needed --noconfirm gimp
pacman -S --needed --noconfirm git
pacman -S --needed --noconfirm gksu
pacman -S --needed --noconfirm gl2ps
pacman -S --needed --noconfirm glew
pacman -S --needed --noconfirm glib-networking
pacman -S --needed --noconfirm glib2
pacman -S --needed --noconfirm glibc
pacman -S --needed --noconfirm glibmm
pacman -S --needed --noconfirm glu
pacman -S --needed --noconfirm gmp
pacman -S --needed --noconfirm gnome-icon-theme
pacman -S --needed --noconfirm gnome-icon-theme-symbolic
pacman -S --needed --noconfirm gnome-keyring
pacman -S --needed --noconfirm gnome-menus
pacman -S --needed --noconfirm gnome-themes-standard
pacman -S --needed --noconfirm gnupg
pacman -S --needed --noconfirm gnutls
pacman -S --needed --noconfirm gobject-introspection-runtime
pacman -S --needed --noconfirm gparted
pacman -S --needed --noconfirm gpgme
pacman -S --needed --noconfirm gpm
pacman -S --needed --noconfirm gptfdisk
pacman -S --needed --noconfirm graphene
pacman -S --needed --noconfirm graphite
pacman -S --needed --noconfirm graphviz
pacman -S --needed --noconfirm grep
pacman -S --needed --noconfirm groff
pacman -S --needed --noconfirm grub
pacman -S --needed --noconfirm gsettings-desktop-schemas
pacman -S --needed --noconfirm gsfonts
pacman -S --needed --noconfirm gsl
pacman -S --needed --noconfirm gsm
pacman -S --needed --noconfirm gssproxy
pacman -S --needed --noconfirm gst-libav
pacman -S --needed --noconfirm gst-plugins-bad
pacman -S --needed --noconfirm gst-plugins-base
pacman -S --needed --noconfirm gst-plugins-base-libs
pacman -S --needed --noconfirm gst-plugins-good
pacman -S --needed --noconfirm gst-plugins-ugly
pacman -S --needed --noconfirm gstreamer
pacman -S --needed --noconfirm gtk-engine-murrine
pacman -S --needed --noconfirm gtk-theme-breath
pacman -S --needed --noconfirm gtk-update-icon-cache
pacman -S --needed --noconfirm gtk-xfce-engine
pacman -S --needed --noconfirm gtk2
pacman -S --needed --noconfirm gtk3
pacman -S --needed --noconfirm gtk3-print-backends
pacman -S --needed --noconfirm gtkmm
pacman -S --needed --noconfirm gtkmm3
pacman -S --needed --noconfirm gtksourceview2
pacman -S --needed --noconfirm gtksourceview3
pacman -S --needed --noconfirm gtkspell
pacman -S --needed --noconfirm gts
pacman -S --needed --noconfirm gufw
pacman -S --needed --noconfirm guile
pacman -S --needed --noconfirm gv
pacman -S --needed --noconfirm gvfs
pacman -S --needed --noconfirm gvfs-afc
pacman -S --needed --noconfirm gvfs-gphoto2
pacman -S --needed --noconfirm gvfs-mtp
pacman -S --needed --noconfirm gvfs-nfs
pacman -S --needed --noconfirm gvfs-smb
pacman -S --needed --noconfirm gzip
pacman -S --needed --noconfirm harfbuzz
pacman -S --needed --noconfirm harfbuzz-icu
pacman -S --needed --noconfirm haveged
pacman -S --needed --noconfirm hdf5
pacman -S --needed --noconfirm hdparm
pacman -S --needed --noconfirm hexchat
pacman -S --needed --noconfirm hicolor-icon-theme
pacman -S --needed --noconfirm hplip
pacman -S --needed --noconfirm hspell
pacman -S --needed --noconfirm htop
pacman -S --needed --noconfirm hunspell
pacman -S --needed --noconfirm hwids
pacman -S --needed --noconfirm hwinfo
pacman -S --needed --noconfirm hyphen
pacman -S --needed --noconfirm iana-etc
pacman -S --needed --noconfirm icu
pacman -S --needed --noconfirm ijs
pacman -S --needed --noconfirm ilmbase
pacman -S --needed --noconfirm imagemagick
pacman -S --needed --noconfirm imlib2
pacman -S --needed --noconfirm inetutils
pacman -S --needed --noconfirm iniparser
pacman -S --needed --noconfirm inotify-tools
pacman -S --needed --noconfirm inputproto
pacman -S --needed --noconfirm intel-tbb
pacman -S --needed --noconfirm intel-ucode
pacman -S --needed --noconfirm intltool
pacman -S --needed --noconfirm inxi
pacman -S --needed --noconfirm iproute2
pacman -S --needed --noconfirm iptables
pacman -S --needed --noconfirm iputils
pacman -S --needed --noconfirm ipw2100-fw
pacman -S --needed --noconfirm ipw2200-fw
pacman -S --needed --noconfirm ipython
pacman -S --needed --noconfirm iso-codes
pacman -S --needed --noconfirm iw
pacman -S --needed --noconfirm jack
pacman -S --needed --noconfirm jansson
pacman -S --needed --noconfirm jasper
pacman -S --needed --noconfirm java-environment-common
pacman -S --needed --noconfirm java-runtime-common
pacman -S --needed --noconfirm jbig2dec
pacman -S --needed --noconfirm jdk8-openjdk
pacman -S --needed --noconfirm jfsutils
pacman -S --needed --noconfirm jre8-openjdk
pacman -S --needed --noconfirm jre8-openjdk-headless
pacman -S --needed --noconfirm json-glib
pacman -S --needed --noconfirm jsoncpp
pacman -S --needed --noconfirm jupyter
pacman -S --needed --noconfirm jupyter-nbformat
pacman -S --needed --noconfirm jupyter-notebook
pacman -S --needed --noconfirm jupyter-widgetsnbextension
pacman -S --needed --noconfirm jupyter_console
pacman -S --needed --noconfirm kauth
pacman -S --needed --noconfirm kbd
pacman -S --needed --noconfirm kbproto
pacman -S --needed --noconfirm kcoreaddons
pacman -S --needed --noconfirm keyutils
pacman -S --needed --noconfirm kitemmodels
pacman -S --needed --noconfirm kmod
pacman -S --needed --noconfirm kplotting
pacman -S --needed --noconfirm krb5
pacman -S --needed --noconfirm l-smash
pacman -S --needed --noconfirm ladspa
pacman -S --needed --noconfirm lame
pacman -S --needed --noconfirm lapack
pacman -S --needed --noconfirm lcms
pacman -S --needed --noconfirm lcms2
pacman -S --needed --noconfirm ldb
pacman -S --needed --noconfirm ldns
pacman -S --needed --noconfirm leptonica
pacman -S --needed --noconfirm less
pacman -S --needed --noconfirm libabw
pacman -S --needed --noconfirm libaio
pacman -S --needed --noconfirm libarchive
pacman -S --needed --noconfirm libass
pacman -S --needed --noconfirm libassuan
pacman -S --needed --noconfirm libasyncns
pacman -S --needed --noconfirm libatasmart
pacman -S --needed --noconfirm libatomic_ops
pacman -S --needed --noconfirm libavc1394
pacman -S --needed --noconfirm libblockdev
pacman -S --needed --noconfirm libbluray
pacman -S --needed --noconfirm libbsd
pacman -S --needed --noconfirm libburn
pacman -S --needed --noconfirm libbytesize
pacman -S --needed --noconfirm libcaca
pacman -S --needed --noconfirm libcanberra
pacman -S --needed --noconfirm libcanberra-pulse
pacman -S --needed --noconfirm libcap
pacman -S --needed --noconfirm libcap-ng
pacman -S --needed --noconfirm libcddb
pacman -S --needed --noconfirm libcdio
pacman -S --needed --noconfirm libcdio-paranoia
pacman -S --needed --noconfirm libcdr
pacman -S --needed --noconfirm libcmis
pacman -S --needed --noconfirm libcroco
pacman -S --needed --noconfirm libcups
pacman -S --needed --noconfirm libdaemon
pacman -S --needed --noconfirm libdatrie
pacman -S --needed --noconfirm libdc1394
pacman -S --needed --noconfirm libdca
pacman -S --needed --noconfirm libdnet
pacman -S --needed --noconfirm libdrm
pacman -S --needed --noconfirm libdv
pacman -S --needed --noconfirm libdvbpsi
pacman -S --needed --noconfirm libdvdcss
pacman -S --needed --noconfirm libdvdnav
pacman -S --needed --noconfirm libdvdread
pacman -S --needed --noconfirm libe-book
pacman -S --needed --noconfirm libebml
pacman -S --needed --noconfirm libedit
pacman -S --needed --noconfirm libelf
pacman -S --needed --noconfirm libepoxy
pacman -S --needed --noconfirm libetonyek
pacman -S --needed --noconfirm libevdev
pacman -S --needed --noconfirm libevent
pacman -S --needed --noconfirm libexif
pacman -S --needed --noconfirm libexttextcat
pacman -S --needed --noconfirm libfbclient
pacman -S --needed --noconfirm libfdk-aac
pacman -S --needed --noconfirm libffi
pacman -S --needed --noconfirm libfontenc
pacman -S --needed --noconfirm libgadu
pacman -S --needed --noconfirm libgcrypt
pacman -S --needed --noconfirm libglade
pacman -S --needed --noconfirm libglvnd
pacman -S --needed --noconfirm libgme
pacman -S --needed --noconfirm libgnome-keyring
pacman -S --needed --noconfirm libgpg-error
pacman -S --needed --noconfirm libgphoto2
pacman -S --needed --noconfirm libgsf
pacman -S --needed --noconfirm libgtop
pacman -S --needed --noconfirm libgudev
pacman -S --needed --noconfirm libguess
pacman -S --needed --noconfirm libgusb
pacman -S --needed --noconfirm libical
pacman -S --needed --noconfirm libice
pacman -S --needed --noconfirm libid3tag
pacman -S --needed --noconfirm libidn
pacman -S --needed --noconfirm libiec61883
pacman -S --needed --noconfirm libimobiledevice
pacman -S --needed --noconfirm libinput
pacman -S --needed --noconfirm libiodbc
pacman -S --needed --noconfirm libisofs
pacman -S --needed --noconfirm libixion
pacman -S --needed --noconfirm libjpeg-turbo
pacman -S --needed --noconfirm libkate
pacman -S --needed --noconfirm libksba
pacman -S --needed --noconfirm liblangtag
pacman -S --needed --noconfirm libldap
pacman -S --needed --noconfirm liblouis
pacman -S --needed --noconfirm liblqr
pacman -S --needed --noconfirm libmad
pacman -S --needed --noconfirm libmariadbclient
pacman -S --needed --noconfirm libmatroska
pacman -S --needed --noconfirm libmbim
pacman -S --needed --noconfirm libmm-glib
pacman -S --needed --noconfirm libmms
pacman -S --needed --noconfirm libmng
pacman -S --needed --noconfirm libmnl
pacman -S --needed --noconfirm libmodplug
pacman -S --needed --noconfirm libmp4v2
pacman -S --needed --noconfirm libmpc
pacman -S --needed --noconfirm libmpcdec
pacman -S --needed --noconfirm libmpd
pacman -S --needed --noconfirm libmpeg2
pacman -S --needed --noconfirm libmspack
pacman -S --needed --noconfirm libmspub
pacman -S --needed --noconfirm libmtp
pacman -S --needed --noconfirm libmwaw
pacman -S --needed --noconfirm libndp
pacman -S --needed --noconfirm libnetfilter_conntrack
pacman -S --needed --noconfirm libnewt
pacman -S --needed --noconfirm libnfnetlink
pacman -S --needed --noconfirm libnfs
pacman -S --needed --noconfirm libnftnl
pacman -S --needed --noconfirm libnghttp2
pacman -S --needed --noconfirm libnice
pacman -S --needed --noconfirm libnl
pacman -S --needed --noconfirm libnm
pacman -S --needed --noconfirm libnm-glib
pacman -S --needed --noconfirm libnotify
pacman -S --needed --noconfirm libodfgen
pacman -S --needed --noconfirm libofa
pacman -S --needed --noconfirm libogg
pacman -S --needed --noconfirm libomxil-bellagio
pacman -S --needed --noconfirm libopenraw
pacman -S --needed --noconfirm liborcus
pacman -S --needed --noconfirm liborigin2
pacman -S --needed --noconfirm libpagemaker
pacman -S --needed --noconfirm libpaper
pacman -S --needed --noconfirm libpcap
pacman -S --needed --noconfirm libpciaccess
pacman -S --needed --noconfirm libpgm
pacman -S --needed --noconfirm libpipeline
pacman -S --needed --noconfirm libplist
pacman -S --needed --noconfirm libpng
pacman -S --needed --noconfirm libproxy
pacman -S --needed --noconfirm libpsl
pacman -S --needed --noconfirm libpthread-stubs
pacman -S --needed --noconfirm libpulse
pacman -S --needed --noconfirm libpurple
pacman -S --needed --noconfirm libqmi
pacman -S --needed --noconfirm libraqm
pacman -S --needed --noconfirm libraw1394
pacman -S --needed --noconfirm librevenge
pacman -S --needed --noconfirm librsvg
pacman -S --needed --noconfirm libsamplerate
pacman -S --needed --noconfirm libsasl
pacman -S --needed --noconfirm libseccomp
pacman -S --needed --noconfirm libsecret
pacman -S --needed --noconfirm libshout
pacman -S --needed --noconfirm libsidplay
pacman -S --needed --noconfirm libsigc++
pacman -S --needed --noconfirm libsigsegv
pacman -S --needed --noconfirm libsm
pacman -S --needed --noconfirm libsndfile
pacman -S --needed --noconfirm libsodium
pacman -S --needed --noconfirm libsoup
pacman -S --needed --noconfirm libsoxr
pacman -S --needed --noconfirm libspectre
pacman -S --needed --noconfirm libspiro
pacman -S --needed --noconfirm libsrtp
pacman -S --needed --noconfirm libssh
pacman -S --needed --noconfirm libssh2
pacman -S --needed --noconfirm libstemmer
pacman -S --needed --noconfirm libsynctex
pacman -S --needed --noconfirm libsystemd
pacman -S --needed --noconfirm libtar
pacman -S --needed --noconfirm libtasn1
pacman -S --needed --noconfirm libteam
pacman -S --needed --noconfirm libthai
pacman -S --needed --noconfirm libtheora
pacman -S --needed --noconfirm libtiff
pacman -S --needed --noconfirm libtiger
pacman -S --needed --noconfirm libtirpc
pacman -S --needed --noconfirm libtommath
pacman -S --needed --noconfirm libtool
pacman -S --needed --noconfirm libunique
pacman -S --needed --noconfirm libunistring
pacman -S --needed --noconfirm libunwind
pacman -S --needed --noconfirm libupnp
pacman -S --needed --noconfirm liburcu
pacman -S --needed --noconfirm libusb
pacman -S --needed --noconfirm libusbmuxd
pacman -S --needed --noconfirm libutil-linux
pacman -S --needed --noconfirm libuv
pacman -S --needed --noconfirm libva
pacman -S --needed --noconfirm libvdpau
pacman -S --needed --noconfirm libvisio
pacman -S --needed --noconfirm libvisual
pacman -S --needed --noconfirm libvoikko
pacman -S --needed --noconfirm libvorbis
pacman -S --needed --noconfirm libvpx
pacman -S --needed --noconfirm libwacom
pacman -S --needed --noconfirm libwbclient
pacman -S --needed --noconfirm libwebp
pacman -S --needed --noconfirm libwmf
pacman -S --needed --noconfirm libwnck
pacman -S --needed --noconfirm libwnck3
pacman -S --needed --noconfirm libwpd
pacman -S --needed --noconfirm libwpg
pacman -S --needed --noconfirm libwps
pacman -S --needed --noconfirm libx11
pacman -S --needed --noconfirm libx264
pacman -S --needed --noconfirm libx264-all
pacman -S --needed --noconfirm libx86emu
pacman -S --needed --noconfirm libxau
pacman -S --needed --noconfirm libxaw
pacman -S --needed --noconfirm libxcb
pacman -S --needed --noconfirm libxcomposite
pacman -S --needed --noconfirm libxcursor
pacman -S --needed --noconfirm libxdamage
pacman -S --needed --noconfirm libxdmcp
pacman -S --needed --noconfirm libxext
pacman -S --needed --noconfirm libxfce4ui
pacman -S --needed --noconfirm libxfce4util
pacman -S --needed --noconfirm libxfixes
pacman -S --needed --noconfirm libxfont
pacman -S --needed --noconfirm libxfont2
pacman -S --needed --noconfirm libxft
pacman -S --needed --noconfirm libxi
pacman -S --needed --noconfirm libxinerama
pacman -S --needed --noconfirm libxkbcommon
pacman -S --needed --noconfirm libxkbcommon-x11
pacman -S --needed --noconfirm libxkbfile
pacman -S --needed --noconfirm libxklavier
pacman -S --needed --noconfirm libxml2
pacman -S --needed --noconfirm libxmu
pacman -S --needed --noconfirm libxp
pacman -S --needed --noconfirm libxpm
pacman -S --needed --noconfirm libxrandr
pacman -S --needed --noconfirm libxrender
pacman -S --needed --noconfirm libxres
pacman -S --needed --noconfirm libxshmfence
pacman -S --needed --noconfirm libxslt
pacman -S --needed --noconfirm libxss
pacman -S --needed --noconfirm libxt
pacman -S --needed --noconfirm libxtst
pacman -S --needed --noconfirm libxv
pacman -S --needed --noconfirm libxxf86misc
pacman -S --needed --noconfirm libxxf86vm
pacman -S --needed --noconfirm libyaml
pacman -S --needed --noconfirm libzmf
pacman -S --needed --noconfirm licenses
pacman -S --needed --noconfirm light-locker
pacman -S --needed --noconfirm lightdm
pacman -S --needed --noconfirm lightdm-gtk-greeter
pacman -S --needed --noconfirm lightdm-gtk-greeter-settings
pacman -S --needed --noconfirm linux-api-headers
pacman -S --needed --noconfirm lldb
pacman -S --needed --noconfirm llvm-libs
pacman -S --needed --noconfirm lm_sensors
pacman -S --needed --noconfirm logrotate
pacman -S --needed --noconfirm lpsolve
pacman -S --needed --noconfirm lsb-release
pacman -S --needed --noconfirm lttng-ust
pacman -S --needed --noconfirm lua
pacman -S --needed --noconfirm lvm2
pacman -S --needed --noconfirm lz4
pacman -S --needed --noconfirm lzo
pacman -S --needed --noconfirm m4
pacman -S --needed --noconfirm make
pacman -S --needed --noconfirm man-db
pacman -S --needed --noconfirm man-pages
pacman -S --needed --noconfirm manjaro-base-skel
pacman -S --needed --noconfirm manjaro-browser-settings
pacman -S --needed --noconfirm manjaro-documentation-en
pacman -S --needed --noconfirm manjaro-firmware
pacman -S --needed --noconfirm manjaro-hello
pacman -S --needed --noconfirm manjaro-hotfixes
pacman -S --needed --noconfirm manjaro-icons
pacman -S --needed --noconfirm manjaro-keyring
pacman -S --needed --noconfirm manjaro-release
pacman -S --needed --noconfirm manjaro-settings-manager
pacman -S --needed --noconfirm manjaro-settings-manager-notifier
pacman -S --needed --noconfirm manjaro-system
pacman -S --needed --noconfirm manjaro-wallpapers-17.0
pacman -S --needed --noconfirm manjaro-xfce-settings
pacman -S --needed --noconfirm mdadm
pacman -S --needed --noconfirm memtest86+
pacman -S --needed --noconfirm menulibre
pacman -S --needed --noconfirm mesa
pacman -S --needed --noconfirm mesa-demos
pacman -S --needed --noconfirm mhwd
pacman -S --needed --noconfirm mhwd-amdgpu
pacman -S --needed --noconfirm mhwd-ati
pacman -S --needed --noconfirm mhwd-catalyst
pacman -S --needed --noconfirm mhwd-db
pacman -S --needed --noconfirm mhwd-nvidia
pacman -S --needed --noconfirm mhwd-nvidia-304xx
pacman -S --needed --noconfirm mhwd-nvidia-340xx
pacman -S --needed --noconfirm mime-types
pacman -S --needed --noconfirm minizip
pacman -S --needed --noconfirm mjpegtools
pacman -S --needed --noconfirm mkinitcpio
pacman -S --needed --noconfirm mkinitcpio-busybox
pacman -S --needed --noconfirm mkinitcpio-openswap
pacman -S --needed --noconfirm mlocate
pacman -S --needed --noconfirm mobile-broadband-provider-info
pacman -S --needed --noconfirm modemmanager
pacman -S --needed --noconfirm mousepad
pacman -S --needed --noconfirm mozilla-common
pacman -S --needed --noconfirm mpfr
pacman -S --needed --noconfirm mpg123
pacman -S --needed --noconfirm mtdev
pacman -S --needed --noconfirm mtpfs
pacman -S --needed --noconfirm mugshot
pacman -S --needed --noconfirm muparser
pacman -S --needed --noconfirm nano
pacman -S --needed --noconfirm ncurses
pacman -S --needed --noconfirm neon
pacman -S --needed --noconfirm net-snmp
pacman -S --needed --noconfirm netcdf
pacman -S --needed --noconfirm nettle
pacman -S --needed --noconfirm network-manager-applet
pacman -S --needed --noconfirm networkmanager
pacman -S --needed --noconfirm networkmanager-dispatcher-ntpd
pacman -S --needed --noconfirm networkmanager-openconnect
pacman -S --needed --noconfirm networkmanager-openvpn
pacman -S --needed --noconfirm networkmanager-pptp
pacman -S --needed --noconfirm networkmanager-vpnc
pacman -S --needed --noconfirm nfs-utils
pacman -S --needed --noconfirm nfsidmap
pacman -S --needed --noconfirm nm-connection-editor
pacman -S --needed --noconfirm npth
pacman -S --needed --noconfirm nspr
pacman -S --needed --noconfirm nss
pacman -S --needed --noconfirm nss-mdns
pacman -S --needed --noconfirm ntfs-3g
pacman -S --needed --noconfirm ntp
pacman -S --needed --noconfirm numlockx
pacman -S --needed --noconfirm ocl-icd
pacman -S --needed --noconfirm open-vm-tools
pacman -S --needed --noconfirm openal
pacman -S --needed --noconfirm openconnect
pacman -S --needed --noconfirm opencore-amr
pacman -S --needed --noconfirm openexr
pacman -S --needed --noconfirm openjpeg2
pacman -S --needed --noconfirm openmotif
pacman -S --needed --noconfirm openresolv
pacman -S --needed --noconfirm openssh
pacman -S --needed --noconfirm openssl
pacman -S --needed --noconfirm openssl-1.0
pacman -S --needed --noconfirm openvpn
pacman -S --needed --noconfirm opus
pacman -S --needed --noconfirm orage
pacman -S --needed --noconfirm orc
pacman -S --needed --noconfirm os-prober
pacman -S --needed --noconfirm p11-kit
pacman -S --needed --noconfirm p7zip
pacman -S --needed --noconfirm pa-applet
pacman -S --needed --noconfirm package-query
pacman -S --needed --noconfirm pacman
pacman -S --needed --noconfirm pacman-mirrors
pacman -S --needed --noconfirm pam
pacman -S --needed --noconfirm pamac
pacman -S --needed --noconfirm pambase
pacman -S --needed --noconfirm pango
pacman -S --needed --noconfirm pangomm
pacman -S --needed --noconfirm parted
pacman -S --needed --noconfirm patch
pacman -S --needed --noconfirm patchutils
pacman -S --needed --noconfirm pavucontrol
pacman -S --needed --noconfirm pciutils
pacman -S --needed --noconfirm pcmciautils
pacman -S --needed --noconfirm pcre
pacman -S --needed --noconfirm pcre2
pacman -S --needed --noconfirm pcsclite
pacman -S --needed --noconfirm perl
pacman -S --needed --noconfirm perl-clone
pacman -S --needed --noconfirm perl-dbi
pacman -S --needed --noconfirm perl-error
pacman -S --needed --noconfirm perl-file-basedir
pacman -S --needed --noconfirm perl-file-desktopentry
pacman -S --needed --noconfirm perl-file-mimeinfo
pacman -S --needed --noconfirm perl-ipc-system-simple
pacman -S --needed --noconfirm perl-parse-yapp
pacman -S --needed --noconfirm perl-uri
pacman -S --needed --noconfirm perl-xml-libxml
pacman -S --needed --noconfirm perl-xml-namespacesupport
pacman -S --needed --noconfirm perl-xml-parser
pacman -S --needed --noconfirm perl-xml-sax
pacman -S --needed --noconfirm perl-xml-sax-base
pacman -S --needed --noconfirm pidgin
pacman -S --needed --noconfirm pinentry
pacman -S --needed --noconfirm pixman
pacman -S --needed --noconfirm pkcs11-helper
pacman -S --needed --noconfirm pkg-config
pacman -S --needed --noconfirm po4a
pacman -S --needed --noconfirm polkit
pacman -S --needed --noconfirm polkit-gnome
pacman -S --needed --noconfirm polkit-qt5
pacman -S --needed --noconfirm poppler
pacman -S --needed --noconfirm poppler-data
pacman -S --needed --noconfirm poppler-glib
pacman -S --needed --noconfirm poppler-qt5
pacman -S --needed --noconfirm popt
pacman -S --needed --noconfirm postgresql-libs
pacman -S --needed --noconfirm potrace
pacman -S --needed --noconfirm powertop
pacman -S --needed --noconfirm ppp
pacman -S --needed --noconfirm pptpclient
pacman -S --needed --noconfirm printproto
pacman -S --needed --noconfirm procps-ng
pacman -S --needed --noconfirm protobuf
pacman -S --needed --noconfirm protobuf-c
pacman -S --needed --noconfirm psmisc
pacman -S --needed --noconfirm pulseaudio
pacman -S --needed --noconfirm pulseaudio-alsa
pacman -S --needed --noconfirm pulseaudio-bluetooth
pacman -S --needed --noconfirm pulseaudio-ctl
pacman -S --needed --noconfirm pulseaudio-zeroconf
pacman -S --needed --noconfirm pygobject-devel
pacman -S --needed --noconfirm pygobject2-devel
pacman -S --needed --noconfirm pygtk
pacman -S --needed --noconfirm pyqt4-common
pacman -S --needed --noconfirm pyqt5-common
pacman -S --needed --noconfirm python
pacman -S --needed --noconfirm python-appdirs
pacman -S --needed --noconfirm python-cairo
pacman -S --needed --noconfirm python-dateutil
pacman -S --needed --noconfirm python-dbus
pacman -S --needed --noconfirm python-dbus-common
pacman -S --needed --noconfirm python-decorator
pacman -S --needed --noconfirm python-distutils-extra
pacman -S --needed --noconfirm python-docopt
pacman -S --needed --noconfirm python-gobject
pacman -S --needed --noconfirm python-ipykernel
pacman -S --needed --noconfirm python-ipywidgets
pacman -S --needed --noconfirm python-jinja
pacman -S --needed --noconfirm python-jsonschema
pacman -S --needed --noconfirm python-jupyter_client
pacman -S --needed --noconfirm python-jupyter_core
pacman -S --needed --noconfirm python-keyutils
pacman -S --needed --noconfirm python-markupsafe
pacman -S --needed --noconfirm python-mistune
pacman -S --needed --noconfirm python-npyscreen
pacman -S --needed --noconfirm python-numpy
pacman -S --needed --noconfirm python-olefile
pacman -S --needed --noconfirm python-packaging
pacman -S --needed --noconfirm python-pexpect
pacman -S --needed --noconfirm python-pickleshare
pacman -S --needed --noconfirm python-pillow
pacman -S --needed --noconfirm python-pip
pacman -S --needed --noconfirm python-prompt_toolkit
pacman -S --needed --noconfirm python-psutil
pacman -S --needed --noconfirm python-ptyprocess
pacman -S --needed --noconfirm python-pygments
pacman -S --needed --noconfirm python-pyparsing
pacman -S --needed --noconfirm python-pyqt5
pacman -S --needed --noconfirm python-pyzmq
pacman -S --needed --noconfirm python-reportlab
pacman -S --needed --noconfirm python-setuptools
pacman -S --needed --noconfirm python-sip
pacman -S --needed --noconfirm python-six
pacman -S --needed --noconfirm python-terminado
pacman -S --needed --noconfirm python-tornado
pacman -S --needed --noconfirm python-traitlets
pacman -S --needed --noconfirm python-wcwidth
pacman -S --needed --noconfirm python-xdg
pacman -S --needed --noconfirm python-yaml
pacman -S --needed --noconfirm python2
pacman -S --needed --noconfirm python2-cairo
pacman -S --needed --noconfirm python2-dbus
pacman -S --needed --noconfirm python2-gobject2
pacman -S --needed --noconfirm python2-pyqt4
pacman -S --needed --noconfirm python2-sip
pacman -S --needed --noconfirm python2-six
pacman -S --needed --noconfirm qbs
pacman -S --needed --noconfirm qpdf
pacman -S --needed --noconfirm qpdfview
pacman -S --needed --noconfirm qrencode
pacman -S --needed --noconfirm qt-assistant-compat
pacman -S --needed --noconfirm qt4
pacman -S --needed --noconfirm qt5-base
pacman -S --needed --noconfirm qt5-declarative
pacman -S --needed --noconfirm qt5-location
pacman -S --needed --noconfirm qt5-quickcontrols
pacman -S --needed --noconfirm qt5-quickcontrols2
pacman -S --needed --noconfirm qt5-script
pacman -S --needed --noconfirm qt5-styleplugins
pacman -S --needed --noconfirm qt5-svg
pacman -S --needed --noconfirm qt5-tools
pacman -S --needed --noconfirm qt5-webchannel
pacman -S --needed --noconfirm qt5-webengine
pacman -S --needed --noconfirm qt5-x11extras
pacman -S --needed --noconfirm qt5-xmlpatterns
pacman -S --needed --noconfirm qt5ct
pacman -S --needed --noconfirm qtcreator
pacman -S --needed --noconfirm qtiplot
pacman -S --needed --noconfirm qwt5
pacman -S --needed --noconfirm qwtplot3d
pacman -S --needed --noconfirm randrproto
pacman -S --needed --noconfirm raptor
pacman -S --needed --noconfirm rasqal
pacman -S --needed --noconfirm readline
pacman -S --needed --noconfirm recordproto
pacman -S --needed --noconfirm redland
pacman -S --needed --noconfirm reiserfsprogs
pacman -S --needed --noconfirm renderproto
pacman -S --needed --noconfirm rest
pacman -S --needed --noconfirm rfkill
pacman -S --needed --noconfirm rhash
pacman -S --needed --noconfirm rpcbind
pacman -S --needed --noconfirm rsync
pacman -S --needed --noconfirm rtkit
pacman -S --needed --noconfirm rtmpdump
pacman -S --needed --noconfirm run-parts
pacman -S --needed --noconfirm s-nail
pacman -S --needed --noconfirm samba
pacman -S --needed --noconfirm sbc
pacman -S --needed --noconfirm schroedinger
pacman -S --needed --noconfirm scrnsaverproto
pacman -S --needed --noconfirm sdl
pacman -S --needed --noconfirm sdl2
pacman -S --needed --noconfirm sdl_image
pacman -S --needed --noconfirm sed
pacman -S --needed --noconfirm serf
pacman -S --needed --noconfirm shadow
pacman -S --needed --noconfirm shared-mime-info
pacman -S --needed --noconfirm sidplay2-libs
pacman -S --needed --noconfirm sip
pacman -S --needed --noconfirm slang
pacman -S --needed --noconfirm smbclient
pacman -S --needed --noconfirm snappy
pacman -S --needed --noconfirm sndio
pacman -S --needed --noconfirm sound-theme-freedesktop
pacman -S --needed --noconfirm soundtouch
pacman -S --needed --noconfirm spandsp
pacman -S --needed --noconfirm speex
pacman -S --needed --noconfirm speexdsp
pacman -S --needed --noconfirm splix
pacman -S --needed --noconfirm sqlite
pacman -S --needed --noconfirm startup-notification
pacman -S --needed --noconfirm subversion
pacman -S --needed --noconfirm sudo
pacman -S --needed --noconfirm sysfsutils
pacman -S --needed --noconfirm systemd
pacman -S --needed --noconfirm systemd-sysvcompat
pacman -S --needed --noconfirm t1lib
pacman -S --needed --noconfirm taglib
pacman -S --needed --noconfirm talloc
pacman -S --needed --noconfirm tamu-anova
pacman -S --needed --noconfirm tar
pacman -S --needed --noconfirm tcc
pacman -S --needed --noconfirm tcl
pacman -S --needed --noconfirm tdb
pacman -S --needed --noconfirm terminus-font
pacman -S --needed --noconfirm tesseract
pacman -S --needed --noconfirm tevent
pacman -S --needed --noconfirm tex-gyre-fonts
pacman -S --needed --noconfirm texinfo
pacman -S --needed --noconfirm texlive-bin
pacman -S --needed --noconfirm thin-provisioning-tools
pacman -S --needed --noconfirm thunar
pacman -S --needed --noconfirm thunar-archive-plugin
pacman -S --needed --noconfirm thunar-media-tags-plugin
pacman -S --needed --noconfirm thunar-volman
pacman -S --needed --noconfirm tlp
pacman -S --needed --noconfirm tslib
pacman -S --needed --noconfirm ttf-bitstream-vera
pacman -S --needed --noconfirm ttf-dejavu
pacman -S --needed --noconfirm ttf-droid
pacman -S --needed --noconfirm ttf-inconsolata
pacman -S --needed --noconfirm ttf-indic-otf
pacman -S --needed --noconfirm ttf-liberation
pacman -S --needed --noconfirm tumbler
pacman -S --needed --noconfirm tzdata
pacman -S --needed --noconfirm udiskie
pacman -S --needed --noconfirm udisks2
pacman -S --needed --noconfirm ufw
pacman -S --needed --noconfirm unace
pacman -S --needed --noconfirm unixodbc
pacman -S --needed --noconfirm unrar
pacman -S --needed --noconfirm unzip
pacman -S --needed --noconfirm upower
pacman -S --needed --noconfirm uriparser
pacman -S --needed --noconfirm usb_modeswitch
pacman -S --needed --noconfirm usbmuxd
pacman -S --needed --noconfirm usbutils
pacman -S --needed --noconfirm util-linux
pacman -S --needed --noconfirm v4l-utils
pacman -S --needed --noconfirm v86d
pacman -S --needed --noconfirm vertex-maia-icon-theme
pacman -S --needed --noconfirm vertex-maia-themes
pacman -S --needed --noconfirm vi
pacman -S --needed --noconfirm vibrancy-colors
pacman -S --needed --noconfirm vid.stab
pacman -S --needed --noconfirm videoproto
pacman -S --needed --noconfirm viewnior
pacman -S --needed --noconfirm vlc-nightly
pacman -S --needed --noconfirm volume_key
pacman -S --needed --noconfirm vpnc
pacman -S --needed --noconfirm vte-common
pacman -S --needed --noconfirm vte3
pacman -S --needed --noconfirm vulkan-icd-loader
pacman -S --needed --noconfirm wavpack
pacman -S --needed --noconfirm wayland
pacman -S --needed --noconfirm wayland-protocols
pacman -S --needed --noconfirm webkit2gtk
pacman -S --needed --noconfirm webrtc-audio-processing
pacman -S --needed --noconfirm wget
pacman -S --needed --noconfirm which
pacman -S --needed --noconfirm wildmidi
pacman -S --needed --noconfirm wireless-regdb
pacman -S --needed --noconfirm wpa_supplicant
pacman -S --needed --noconfirm wxgtk-common
pacman -S --needed --noconfirm wxgtk3
pacman -S --needed --noconfirm x265
pacman -S --needed --noconfirm xaw3d
pacman -S --needed --noconfirm xcb-proto
pacman -S --needed --noconfirm xcb-util
pacman -S --needed --noconfirm xcb-util-image
pacman -S --needed --noconfirm xcb-util-keysyms
pacman -S --needed --noconfirm xcb-util-renderutil
pacman -S --needed --noconfirm xcb-util-wm
pacman -S --needed --noconfirm xcursor-breeze
pacman -S --needed --noconfirm xcursor-simpleandsoft
pacman -S --needed --noconfirm xcursor-vanilla-dmz-aa
pacman -S --needed --noconfirm xdg-su
pacman -S --needed --noconfirm xdg-user-dirs
pacman -S --needed --noconfirm xdg-utils
pacman -S --needed --noconfirm xextproto
pacman -S --needed --noconfirm xf86-input-elographics
pacman -S --needed --noconfirm xf86-input-evdev
pacman -S --needed --noconfirm xf86-input-keyboard
pacman -S --needed --noconfirm xf86-input-libinput
pacman -S --needed --noconfirm xf86-input-mouse
pacman -S --needed --noconfirm xf86-input-vmmouse
pacman -S --needed --noconfirm xf86-input-void
pacman -S --needed --noconfirm xf86-video-vmware
pacman -S --needed --noconfirm xf86miscproto
pacman -S --needed --noconfirm xf86vidmodeproto
pacman -S --needed --noconfirm xfburn
pacman -S --needed --noconfirm xfce4-appfinder
pacman -S --needed --noconfirm xfce4-battery-plugin
pacman -S --needed --noconfirm xfce4-clipman-plugin
pacman -S --needed --noconfirm xfce4-cpufreq-plugin
pacman -S --needed --noconfirm xfce4-cpugraph-plugin
pacman -S --needed --noconfirm xfce4-dict
pacman -S --needed --noconfirm xfce4-diskperf-plugin
pacman -S --needed --noconfirm xfce4-fsguard-plugin
pacman -S --needed --noconfirm xfce4-genmon-plugin
pacman -S --needed --noconfirm xfce4-mailwatch-plugin
pacman -S --needed --noconfirm xfce4-mount-plugin
pacman -S --needed --noconfirm xfce4-mpc-plugin
pacman -S --needed --noconfirm xfce4-netload-plugin
pacman -S --needed --noconfirm xfce4-notes-plugin
pacman -S --needed --noconfirm xfce4-notifyd
pacman -S --needed --noconfirm xfce4-panel
pacman -S --needed --noconfirm xfce4-power-manager
pacman -S --needed --noconfirm xfce4-screenshooter
pacman -S --needed --noconfirm xfce4-sensors-plugin
pacman -S --needed --noconfirm xfce4-session
pacman -S --needed --noconfirm xfce4-settings
pacman -S --needed --noconfirm xfce4-smartbookmark-plugin
pacman -S --needed --noconfirm xfce4-systemload-plugin
pacman -S --needed --noconfirm xfce4-taskmanager
pacman -S --needed --noconfirm xfce4-terminal
pacman -S --needed --noconfirm xfce4-time-out-plugin
pacman -S --needed --noconfirm xfce4-timer-plugin
pacman -S --needed --noconfirm xfce4-verve-plugin
pacman -S --needed --noconfirm xfce4-wavelan-plugin
pacman -S --needed --noconfirm xfce4-weather-plugin
pacman -S --needed --noconfirm xfce4-whiskermenu-plugin
pacman -S --needed --noconfirm xfce4-xkb-plugin
pacman -S --needed --noconfirm xfconf
pacman -S --needed --noconfirm xfdesktop
pacman -S --needed --noconfirm xfsprogs
pacman -S --needed --noconfirm xfwm4
pacman -S --needed --noconfirm xfwm4-themes
pacman -S --needed --noconfirm xineramaproto
pacman -S --needed --noconfirm xkeyboard-config
pacman -S --needed --noconfirm xmlrpc-c
pacman -S --needed --noconfirm xmlstarlet
pacman -S --needed --noconfirm xorg-bdftopcf
pacman -S --needed --noconfirm xorg-font-util
pacman -S --needed --noconfirm xorg-font-utils
pacman -S --needed --noconfirm xorg-fonts-alias
pacman -S --needed --noconfirm xorg-fonts-encodings
pacman -S --needed --noconfirm xorg-fonts-misc
pacman -S --needed --noconfirm xorg-iceauth
pacman -S --needed --noconfirm xorg-mkfontdir
pacman -S --needed --noconfirm xorg-mkfontscale
pacman -S --needed --noconfirm xorg-server
pacman -S --needed --noconfirm xorg-server-common
pacman -S --needed --noconfirm xorg-setxkbmap
pacman -S --needed --noconfirm xorg-twm
pacman -S --needed --noconfirm xorg-xauth
pacman -S --needed --noconfirm xorg-xinit
pacman -S --needed --noconfirm xorg-xkbcomp
pacman -S --needed --noconfirm xorg-xkill
pacman -S --needed --noconfirm xorg-xmodmap
pacman -S --needed --noconfirm xorg-xrdb
pacman -S --needed --noconfirm xorg-xset
pacman -S --needed --noconfirm xplot
pacman -S --needed --noconfirm xproto
pacman -S --needed --noconfirm xvidcore
pacman -S --needed --noconfirm xz
pacman -S --needed --noconfirm yajl
pacman -S --needed --noconfirm yaourt
pacman -S --needed --noconfirm yelp
pacman -S --needed --noconfirm yelp-xsl
pacman -S --needed --noconfirm zd1211-firmware
pacman -S --needed --noconfirm zenity
pacman -S --needed --noconfirm zeromq
pacman -S --needed --noconfirm zimg
pacman -S --needed --noconfirm zip
pacman -S --needed --noconfirm zita-alsa-pcmi
pacman -S --needed --noconfirm zita-resampler
pacman -S --needed --noconfirm zlib
pacman -S --needed --noconfirm zsh
pacman -S --needed --noconfirm zvbi
pacman -S --needed --noconfirm zziplib
